# Generated by Django 3.1.6 on 2021-10-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20211026_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.CharField(default='', max_length=255),
        ),
    ]
