# Generated by Django 3.1.6 on 2021-10-28 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlike',
            old_name='Post',
            new_name='post',
        ),
    ]
