# Generated by Django 3.1.6 on 2021-10-28 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20211028_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlike',
            old_name='is_dislike',
            new_name='is_like',
        ),
    ]
