# Generated by Django 3.1.6 on 2021-10-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20211028_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
    ]
